name: mol-regression-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.19
  - rdkit
  - pip
  - pip:
      - mordred
      - optuna
      - shap
      - lightgbm
      - xgboost==1.6.0
      - scikit-learn
      - matplotlib
      - seaborn
      - pandas
      - jupyter
      - py3Dmol
      - torch
      - torchvision
